version: 2.1

executors:
  android-java17:
    docker:
      - image: cimg/android:2022.04

orbs:
  maven: circleci/maven@1.3.0

jobs:
  build:
    executor: android-java17
    steps:
      - checkout
      - restore_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Set Executable Permission for gradlew
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - save_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
      - run:
          name: Build Project
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file
