version: 2.1

executors:
  android-java17:
    docker:
      - image: cimg/android:2024.01

orbs:
  maven: circleci/maven@1.3.0

jobs:
  build:
    executor: android-java17
    steps:
      - checkout
      - run:
          name: Set JDK 17
          command: |
            sudo apt update && sudo apt install -y openjdk-17-jdk
            echo "export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $BASH_ENV
            echo "export PATH=\$JAVA_HOME/bin:\$PATH" >> $BASH_ENV
            source $BASH_ENV
            java -version
      - restore_cache:
          key: gradle-cache-{{ checksum "build.gradle.kts" }}
      - run:
          name: Set Executable Permission for gradlew
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - save_cache:
          key: gradle-cache-{{ checksum "build.gradle.kts" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
      - run:
          name: Build Project
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file
